### ISSUE TITLE
Window size bug

### ISSUE THREAD

**Issue by AlexTalker** [GeorgeFilipkin/pulsemixer#11] opened 2016-02-21 21:14 UTC
![2016-02-22-001258_1366x768_scrot](https://cloud.githubusercontent.com/assets/3531127/13205439/22c37c8e-d8f9-11e5-9231-393abaa34338.png)

Bigger than WHAT? 1366x768 ( a little less, but this doesn't matter ) isn't bigger enough?

**Comment by AlexTalker** [comment] 2016-02-21 21:21
Funny, if number button, it show interface. Strange. Seems like first time app running u meet the error, otherwise no.
![2016-02-22-002056_1366x768_scrot](https://cloud.githubusercontent.com/assets/3531127/13205475/29911552-d8fa-11e5-88fa-512ec92a58ba.png)

**Comment by AlexTalker** [comment] 2016-02-21 21:37
Dammit, don't know how to reproduce that...

**Comment by GeorgeFilipkin** [comment] 2016-02-23 16:45
So did you manage to reproduce the bug? Because I did not.

**Comment by AlexTalker** [comment] 2016-02-23 17:07
I didn't too. Seems like the bug is able only when you first time ran the app.

**Comment by GeorgeFilipkin** [comment] 2016-02-23 18:31
Well if you (or anyone else) will ever stumble on this problem again - try running [this modified version](https://gist.github.com/GeorgeFilipkin/09d498b1404f53c05a80). It should end curses interface and dump full traceback along with the content of problematic line. I'm leaving the issue open until then.

**Comment by AlexTalker** [comment] 2016-02-27 14:44
@GeorgeFilipkin sure, as only meet this problem again :smile: thanks for maintain the useful thing :+1:

**Comment by GeorgeFilipkin** [comment] 2016-03-09 11:54
I've found a very similar issue in qterminal (https://github.com/lxde/qterminal/issues/39), but is't closed due to lack of feedback. So it might have been some sneaky qterminal bug. Ever noticed this behavior anywhere besides pulsemixer?

**Comment by AlexTalker** [comment] 2016-03-09 15:39
@GeorgeFilipkin No, I didn't. Strange. The only bug I meet before is great lack of memory in qterminal(34% RAM was record for my 8GiB :smile: ).
Hm. Wait, might I meet it when play around curses examples but I unsure...Sorry :disappointed:

**Comment by wrtlprnft** [comment] 2016-05-05 18:53
This is what I get, although it doesn't happen upon starting the program, but instead when I use kmixer's global hotkeys to change the volume while pulsemixer is running:

```
['  File "./pulsemixer-dbg", line 1215, in display_line\n'
 "    self.screen.addstr(index, shift, ''.join(p[:-1]), int(p[-1]) | mod)\n",
 [2,
  348,
  ' |0\n'
  '                                                                    '
  '|768\n'
  ' |1048576\n'
  ' 152|0\n'
  '  |2097152\n'
  '└|0\n'
  '⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛|256\n'
  '⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛|512\n'
  '⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛|768\n'
  '┘|0\n'
  '|2097152']]
```
I'm running it inside a screen-4.03.01 using konsole-2.14.2.

**Comment by GeorgeFilipkin** [comment] 2016-05-06 14:55
@wrtlprnft Hey, thanks for the report. I still could not reproduce the bug, but have found some other issue when using konsole and they are probably related. Can you try [this version](https://gist.github.com/GeorgeFilipkin/1e9dd60a224d9b7e89f9d01ca727053b) and see if your problem still persists? Want to be sure before pushing to master.

**Comment by wrtlprnft** [comment] 2016-05-08 08:34
I think this fixes it, at least I can't get it to crash anymore.

There still is a list index bug, but it's probably unrelated: In the menu that pops up when pressing return on an audio sink, select _Set port_ and then move the cursor one beyond the last available port. Pressing return then triggers a “Can you make it any bigger” message.

**Comment by GeorgeFilipkin** [comment] 2016-05-10 12:24
Everything should be fixed now. Considering the issue closed.

**Closed by GeorgeFilipkin** 2016-05-10 12:24 UTC
Labels: help wanted
